# GoReleaser configuration for Autocommit
# Documentation: https://goreleaser.com

version: 2

# Basic project metadata
project_name: autocommit

before:
  hooks:
    # Run tests before building
    - go test ./...
    # Ensure dependencies are up to date
    - go mod tidy

builds:
  - id: autocommit
    # Main package to build
    main: ./cmd/autocommit
    binary: autocommit

    # Build for multiple platforms
    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Build flags
    flags:
      - -trimpath

    ldflags: >-
      -s -w
      -X main.version={{.Version}}
      -X main.commit={{.Commit}}
      -X main.date={{.Date}}
      -X 'main.builtBy={{ .Env.BUILT_BY }}'

    env:
      - CGO_ENABLED=0

archives:
  - id: autocommit-archive

    # Archive name template
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  # Generate checksums file
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  # Generate changelog from git commits
  sort: asc
  use: github

  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - 'typo'

  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

release:
  # GitHub release configuration
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"

  # Draft release (change to false to auto-publish)
  draft: false

  # Mark as prerelease if version contains - (e.g., v1.0.0-beta)
  prerelease: auto

  # Release name
  name_template: "Release {{.Version}}"

  # Header and footer for release notes
  header: |
    ## Autocommit {{.Version}}

    Download the appropriate binary for your platform below.

  footer: |
    ---

    ## Installation

    ### macOS / Linux
    ```bash
    # Download the appropriate archive for your system
    tar -xzf autocommit_{{.Version}}_<os>_<arch>.tar.gz

    # Move to your PATH
    sudo mv autocommit /usr/local/bin/

    # Verify installation
    autocommit --version
    ```

    ### Windows
    ```powershell
    # Extract the zip file and add autocommit.exe to your PATH
    ```

    ## Full Changelog

    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/autocommit/compare/{{ .PreviousTag }}...{{.Tag}}

brews:
  - name: autocommit
    repository:
      owner: jsmenzies
      name: homebrew-autocommit
      token: "{{ .Env.HOMEBREW_AUTOCOMMIT_TOKEN }}"
    directory: Formula
    commit_author:
      name: James Menzies
      email: jsmenzies@users.noreply.github.com
    description: "AI-powered git commit message generator"
    homepage: "https://github.com/jsmenzies/autocommit"
    license: "MIT"
    install: |
      bin.install "autocommit"

scoops:
  - repository:
      owner: jsmenzies
      name: scoop-autocommit
      token: "{{ .Env.HOMEBREW_AUTOCOMMIT_TOKEN }}"

    commit_author:
      name: James Menzies
      email: jsmenzies@users.noreply.github.com

    homepage: "https://github.com/jsmenzies/autocommit"
    description: "AI-powered git commit message generator"
    license: "MIT"
